name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - trfore
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: shell-code
    attributes:
      label: Relevant code
      description: Please copy and paste any relevant shell code. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: input
    id: proxmox-version
    attributes:
      label: Proxmox version
      description: What version of Proxmox are you running? Please paste the output of `pveversion`
      placeholder: "pve-manager/7.4-17/513c62be (running kernel: 5.15.149-1-pve)"
    validations:
      required: true
